# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Hilman Kurniawan
title: DevOps Engineer
email: hire.hilmankurniawan@gmail.com
phone: 081908333188
website: hilmankurniawan.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: hilman-k8n
linkedin_username: kurniawanh


# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Experienced as DevOps Engineer. 5+ years linux experience with multiple distros. Mostly working with clouds (<mark>AWS</mark> & <mark>GCP</mark>) to automate <mark>CI/CD</mark> with <mark>immutable infrastucture</mark>. Experienced using modern monitoring tools and logging (<mark>Datadog</mark>, <mark>Kibana</mark>) to maintain <mark>SLOs</mark> for microservices. Love to code with <mark>Python</mark> / <mark>Java</mark>
  
  Currently learning on Frontend and sometimes blogging.

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
education_title: Education / Certification #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  
  ## Skills:
  
  | Programming       |        |
  |-------------------|--------|
  | Python            | ★★★★★  |
  | Java              | ★★★★☆  |
  | Bash              | ★★★★☆  |
  
  | Automation Server |        |
  |-------------------|--------|
  | Jenkins           | ★★★★★  |
  | GoCD              | ★★★★☆  |

  | Configuration Management |        |
  |--------------------------|--------|
  | Ansible                  | ★★★★★  |
  | Terrform                 | ★★★★☆  |
  
  | Cloud                    |        |
  |--------------------------|--------|
  | Google Cloud Platform    | ★★★★☆  |
  | Amazon Web Services      | ★★★★☆  |
  
  | Relational Database      |        |
  |--------------------------|--------|
  | MySQL                    | ★★★★★  |
  | PostgreSQL               | ★★★★☆  |
  
  | Containerization         |        |
  |--------------------------|--------|
  | Kubernetes               | ★★★★☆  |
  | Openshift                | ★★★★☆  |
  | Docker                   | ★★★★☆  |
  
  | VPN                      |        |
  |--------------------------|--------|
  | OpenVPN                  | ★★★★★  |
  | WireGuard                | ★★★★★  |
  
  | Others                   |        |
  |--------------------------|--------|
  | Nginx                    | ★★★★★  |
  | GitLab                   | ★★★★★  |
  | Python Flask             | ★★★★★  |
  | Datadog                  | ★★★★★  |
  | Wordpress                | ★★★★☆  |
  
  
# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
